import Header from "@/app/components/Header";
import { Hind_Siliguri } from "next/font/google";
import Footer from "./components/Footer";
import "./globals.css";

const hindSiliguri = Hind_Siliguri({
  subsets: ["latin"],
  weight: ["400","500","600","700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${hindSiliguri.className}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
